### ISSUE TITLE
Define and Create Database Schema

### ISSUE THREAD

**Issue by jimmitjoo** [jimmitjoo/livestream-results#1]
Create the necessary tables in the database.
Tables: timing_results, participants, events, participant_events.

**Tasks:**
- [x]  Define the schema for timing_results table.
- [x]  Define the schema for participants table.
- [x]  Define the schema for events table.
- [x]  Define the schema for participant_events table.
- [x]  Implement the schema in the database.
