### ISSUE TITLE
Create Web Interface for File Selection

### ISSUE THREAD

**Issue by jimmitjoo** [jimmitjoo/livestream-results#4]
Build a web interface to allow users to select the timing data file and the Google Sheets file.

**Tasks:**

- [x]  Set up a basic web server using Go.
- [x]  Create an HTML form to upload the timing data file.
- [x]  Handle file upload and initiate file watcher.
- [ ]  Create a form to input the Google Sheets file details for exporting results.
